name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - plyfile
  - pip
  - tqdm
  - intel-openmp
  - ninja  # Required for compiling CUDA extensions